version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    labels:
      - "area/dependencies"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    open-pull-requests-limit: 10
    groups:
      k8s.io:
        patterns:
          - "k8s.io/api"
          - "k8s.io/apimachinery"
          - "k8s.io/client-go"
          - "k8s.io/klog/v2"
      sigs.k8s.io:
        patterns:
          - "sigs.k8s.io/controller-runtime"
          - "sigs.k8s.io/e2e-framework"

  - package-ecosystem: "docker"
    directory: "/"
    labels:
      - "area/dependencies"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "area/dependencies"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    open-pull-requests-limit: 10
