version: "3.9"

services:
  vault:
    image: hashicorp/vault:1.13.3
    ports:
      - 127.0.0.1:8200:8200
    environment:
      SKIP_SETCAP: true
      VAULT_DEV_ROOT_TOKEN_ID: 227e1cce-6bf7-30bb-2d2a-acc854318caf
