apiVersion: v2
type: application
name: vault-secrets-webhook
version: 1.20.0-dev.1
appVersion: 1.19.0
description: A Kubernetes mutating webhook that makes direct secret injection into Pods possible
icon: https://raw.githubusercontent.com/banzaicloud/bank-vaults/main/docs/images/logo/bank-vaults-logo.svg
keywords:
  - vault
  - hashicorp
  - secret
  - webhook
home: https://bank-vaults.dev
sources:
  - https://github.com/hashicorp/vault
  - https://github.com/bank-vaults/vault-secrets-webhook
maintainers:
  - name: Bank Vaults Maintainers
    email: team@bank-vaults.dev
