blank_issues_enabled: true
contact_links:
  - name: 📖 Documentation enhancement
    url: https://github.com/bank-vaults/bank-vaults.dev/issues
    about: Suggest an improvement to the documentation

  - name: 📚 Documentation
    url: https://bank-vaults.dev/docs/mutating-webhook/
    about: Check the documentation for help

  - name: 💬 Slack channel
    url: https://eti.cisco.com/slack
    about: Please ask and answer questions here
